---
  - name: Install PIP requirements
    pip: requirements={{ app_path }}/../requirements.txt
    sudo: yes

  - name: collectstatic for Django
    django_manage: command=collectstatic app_path={{ app_path }}

  - name: run migrations for Django in dev
    django_manage: command=migrate app_path={{ app_path }}
    when: app_path == "/vagrant"

  - name: create virtual host file
    template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf
    sudo: yes

  - name: a2ensite {{ domain }}
    command: a2ensite {{ domain }}
    args:
      creates: /etc/apache2/sites-enabled/{{ domain }}.conf
    notify:
      - restart apache2
    sudo: yes
