---
  - name: Install Django
    pip: name=Django==1.8
    sudo: yes

  - name: Install Django REST
    pip: name=djangorestframework
    sudo: yes

  - name: Install Markdown (for browsable API)
    pip: name=markdown
    sudo: yes

  - name: Install Whitenoise
    pip: name=whitenoise
    sudo: yes


  - name: collectstatic for Django
    django_manage: command=collectstatic app_path=/vagrant/{{ main_app }}
