---
  - name: Install PIP requirements
    pip: requirements={{ app_path }}/../requirements.txt
    sudo: yes

  - name: collectstatic for Django
    django_manage: command=collectstatic app_path={{ app_path }}