---
  - name: Install Django
    pip: name=Django==1.8
    sudo: yes

  - name: Install Django REST
    pip: name=djangorestframework
    sudo: yes

  - name: Install Markdown (for browsable API)
    pip: name=markdown
    sudo: yes

  - name: Install Factory Boy for testing
    pip: name=factory_boy
    sudo: yes

  - name: Install Pep 8 Testing
    pip: name=django-test-pep8
    sudo: yes

  - name: Install Whitenoise
    pip: name=whitenoise
    sudo: yes

  - name: Install NetAddr for IP ranges
    pip: name=netaddr
    sudo: yes

  - name: Install Numpy for Pandas
    pip: name=numpy version=1.7.1
    sudo: yes

  - name: Install Pandas
    pip: name=pandas
    sudo: yes

  - name: Install Django Pandas
    pip: name=django-pandas
    sudo: yes

  - name: Install Django REST Pandas for exports
    pip: name=rest-pandas
    sudo: yes


  - name: collectstatic for Django
    django_manage: command=collectstatic app_path={{ app_path }}