language: python
python:
  - "2.7"
env:
  - DJANGO=1.8 DJANGO_SETTINGS_MODULE="holocron_api.travis_settings"
install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements.txt
  - pip install -q flake8
  - pip install -q coveralls
before_script:
  - flake8 --exclude 'migrations' --max-complexity 10 holocron_api
  - python ./holocron_api/manage.py makemigrations
  - python ./holocron_api/manage.py migrate
script:
  coverage run --source=holocron_api ./holocron_api/manage.py test api
after_success:
  coveralls

# Whitelisting branches
# branches:
#   only:
#   - master

