---
    - name: Update apt cache
      apt: update-cache=yes cache_valid_time=86400
      sudo: yes

    - name: Update all packages
      apt: upgrade=dist
      sudo: yes

    - name: install basic packages
      sudo: yes
      apt: pkg={{ item }} state=latest
      tags: [packages]
      with_items:
        - curl
        - vim
        - libxslt1-dev
        - libxml2-dev
        - unzip
        - python-pip
        - python-psycopg2
        - git
        - ntp
        - apache2
        - apache2-mpm-prefork
        - apache2-utils
        - openssl
        - ssl-cert
        - libexpat1
        - libapache2-mod-wsgi
        - postgresql

    - name: Check NTP service to make sure it's running
      service: name=ntp state=started enabled=yes
      sudo: yes

    - name: Check Apache service to make sure it's running
      service: name=apache2 state=started enabled=yes
      sudo: yes

    - name: Install ufw
      apt: name=ufw
    - name: Allow ssh through firewall
      ufw: proto=tcp port=22 rule=allow
    - name: Set ufw policy
      ufw: state=enabled direction=incoming policy=deny
    - name: Allow apache firewall
      ufw: proto=tcp port=80 rule=allow
    - name: Allow apache ssl firewall
      ufw: proto=tcp port=443 rule=allow

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: a2ensite ssl
      command: a2enmod ssl
      notify:
        - restart apache2

    - name: check for SSL folder
      stat: path=/etc/apache2/ssl
      register: ssl_path

    - name: create SSL folder
      command: mkdir /etc/apache2/ssl
      when: ssl_path.stat.exists == false

    - name: apache2 NameVirtualHost Port
      lineinfile: dest=/etc/apache2/ports.conf regexp="^NameVirtualHost " line="" state=present
      notify:
        - restart apache2

    - name: apache2 listen on Specified Port
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="" state=present
      notify:
        - restart apache2

    - name: create virtual host file
      template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}
      sudo: yes

    - name: apache2 virtualhost on Specified Port
      lineinfile: dest=/etc/apache2/sites-available/{{ domain }} regexp="^<VirtualHost \*:" line="<VirtualHost *:{{ http_port }}>"
      notify:
        - restart apache2

    - name: check for Default file
      stat: path=/etc/apache2/sites-enabled/000-default
      register: default_file_check

    - name: delete default file
      command: rm /etc/apache2/sites-enabled/000-default
      when: default_file_check.stat.exists
      sudo: yes
      notify:
        - restart apache2

    - name: a2ensite {{ domain }}
      command: a2ensite {{ domain }}
      args:
        creates: /etc/apache2/sites-enabled/{{ domain }}.conf
      notify:
        - restart apache2