---
    - name: Update apt cache
      apt: update-cache=yes cache_valid_time=86400
      sudo: yes

    - name: Update all packages
      apt: upgrade=dist
      sudo: yes

    - name: install basic packages
      sudo: yes
      apt: pkg={{ item }} state=latest
      tags: [packages]
      with_items:
        - curl
        - vim
        - libxslt1-dev
        - libxml2-dev
        - unzip
        - python-pip
        - python-psycopg2
        - git
        - ntp
        - openssl
        - ssl-cert
        - libexpat1
        - libapache2-mod-wsgi
        - python-numpy
        - python-scipy
        - python-pandas

    - name: Check NTP service to make sure it's running
      service: name=ntp state=started enabled=yes
      sudo: yes

    - name: Install ufw
      apt: name=ufw
    - name: Allow ssh through firewall
      ufw: proto=tcp port=22 rule=allow
    - name: Set ufw policy
      ufw: state=enabled direction=incoming policy=deny
    - name: Allow apache firewall
      ufw: proto=tcp port=80 rule=allow
    - name: Allow apache ssl firewall
      ufw: proto=tcp port=443 rule=allow
