---
- hosts: all
  sudo: true
  vars:
    apache_listen_port: 80
    apache_listen_port_ssl: 443
    apache_create_vhosts: false
    apache_remove_default_vhosts: true
    http_port: 443
    domain: holocron-api.com
    project: holocron-api
    app_path: /holocron-api/holocron_api
    app: api
    APACHE_LOG_DIR: /var/log/apache2
    dbname: holocron
    dbuser: django-test
    dbpassword: testing
    dbpassword_env: "{{ lookup('env','HOLOCRON_DB_PASS') }}"
    # for when we switch to gearlingguy's apache role
    apache_mods_enabled:
      - headers.load
      - rewrite.load
      - ssl.load
      - wsgi.load
    apache_mods_disabled: []
  tasks:

  roles:
  - { role: base }
  - { role: geerlingguy.apache }
  - { role: django, domain: "{{ domain }}" }