---
- hosts: all
  sudo: true
  vars:
    http_port: 443
    domain: holocron-api.com
    project: holocron-api
    app_path: /vagrant/holocron_api
    app: api
    APACHE_LOG_DIR: /var/log/apache2
    dbname: holocron
    dbuser: django-test
    dbpassword: testing
    apache_mods_enabled:
      - header.load
      - rewrite.load
      - ssl.load
    apache_mods_disabled: []
  tasks:

  roles:
  - { role: base }
  - { role: db }
  - { role: django }