---
- hosts: all
  sudo: true
  vars:
    http_port: 443
    domain: holocron-api.com
    project: holocron-api
    main_app: holocron_api
    app: api
    APACHE_LOG_DIR: /var/log/apache2
  tasks:

  roles:
  - { role: base }
  - { role: django }