---
  - name: Install PostGres
    postgresql_db: name={{dbname}}
    sudo: yes
    sudo_user: postgres

  - name: ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL
    sudo: yes
    sudo_user: postgres